import React, { useEffect, createContext, useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';

import SelectedItem from '../contexts/SelectedItems';

import SelectedMovie from '../components/home/SelectedMovie';
import MovieList from '../components/home/MovieList';
import SendMovie from '../components/home/SendMovie';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<SelectedItem>
				<main className={styles.main}>
					<SelectedMovie />
					<MovieList />
					<SendMovie />
				</main>
			</SelectedItem>
		</div>
	);
}
